ALTER TABLE "Transport" ADD COLUMN "depLat" DOUBLE PRECISION;
ALTER TABLE "Transport" ADD COLUMN "depLng" DOUBLE PRECISION;
ALTER TABLE "Transport" ADD COLUMN "arrLat" DOUBLE PRECISION;
ALTER TABLE "Transport" ADD COLUMN "arrLng" DOUBLE PRECISION;
