import type { DemoGlobe } from "./types";

export const GLOBE_MARKER_KEYS = {
  versailles: "globe:versailles",
  kemi: "globe:kemi",
  zugspitze: "globe:zugspitze",
  cinque: "globe:cinque",
  hogmanay: "globe:hogmanay",
  interlaken: "globe:interlaken",
  fushimi: "globe:fushimi",
  tokyoTower: "globe:tokyo-tower",
  machu: "globe:machu",
  sahara: "globe:sahara",
  oktoberfest: "globe:oktoberfest",
  iceland: "globe:iceland",
  dublin: "globe:dublin",
} as const;

export function buildGlobe(): DemoGlobe {
  return {
    createdBy: "you",
    members: [
      { user: "you", role: "owner" },
      { user: "partner", role: "member" },
    ],
    invites: [{ email: "friend@example.com", role: "member" }],
    markers: [
      {
        key: GLOBE_MARKER_KEYS.versailles,
        title: "Palace of Versailles",
        category: "SIGHTSEEING",
        note: "Book tickets in advance — crowds are brutal in summer.",
        lat: 48.8049,
        lng: 2.1204,
        city: "Versailles",
        country: "France",
        countryCode: "fr",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.kemi,
        title: "SnowHotel, Kemi",
        category: "ACTIVITY",
        note: "Rebuilt every December; stay must be Jan–Apr.",
        lat: 65.7356,
        lng: 24.5641,
        city: "Kemi",
        country: "Finland",
        countryCode: "fi",
        createdBy: "partner",
      },
      {
        key: GLOBE_MARKER_KEYS.zugspitze,
        title: "Zugspitze summit",
        category: "ACTIVITY",
        lat: 47.4211,
        lng: 10.9853,
        city: "Grainau",
        country: "Germany",
        countryCode: "de",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.cinque,
        title: "Cinque Terre",
        category: "SIGHTSEEING",
        link: "https://www.cinqueterre.eu.com/en/cinque-terre-itinerary",
        lat: 44.1461,
        lng: 9.6439,
        city: "Riomaggiore",
        country: "Italy",
        countryCode: "it",
        createdBy: "partner",
      },
      {
        key: GLOBE_MARKER_KEYS.hogmanay,
        title: "Edinburgh Hogmanay",
        category: "NIGHTLIFE",
        timing: "31 Dec",
        lat: 55.9533,
        lng: -3.1883,
        city: "Edinburgh",
        country: "United Kingdom",
        countryCode: "gb",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.interlaken,
        title: "Interlaken paragliding",
        category: "ACTIVITY",
        timing: "summer",
        lat: 46.6863,
        lng: 7.8632,
        city: "Interlaken",
        country: "Switzerland",
        countryCode: "ch",
        createdBy: "partner",
      },
      {
        key: GLOBE_MARKER_KEYS.fushimi,
        title: "Fushimi Inari shrine",
        category: "SIGHTSEEING",
        lat: 34.9671,
        lng: 135.7727,
        city: "Kyoto",
        country: "Japan",
        countryCode: "jp",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.tokyoTower,
        title: "Tokyo Tower",
        category: "SIGHTSEEING",
        link: "https://www.tokyotower.co.jp/en/",
        lat: 35.6586,
        lng: 139.7454,
        city: "Tokyo",
        country: "Japan",
        countryCode: "jp",
        createdBy: "partner",
      },
      {
        key: GLOBE_MARKER_KEYS.machu,
        title: "Machu Picchu",
        category: "SIGHTSEEING",
        note: "Book Inca Trail permits months ahead.",
        lat: -13.1631,
        lng: -72.545,
        city: "Aguas Calientes",
        country: "Peru",
        countryCode: "pe",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.sahara,
        title: "Sahara overnight camp",
        category: "ACTIVITY",
        lat: 31.0,
        lng: -4.0,
        city: "Merzouga",
        country: "Morocco",
        countryCode: "ma",
        createdBy: "partner",
        attachments: [
          {
            targetType: "MARKER",
            targetKey: GLOBE_MARKER_KEYS.sahara,
            filename: "sahara-itinerary.txt",
            mime: "text/plain",
            body: "Day 1: Camel trek to camp. Day 2: Sunrise dunes, return by 4x4.",
          },
        ],
      },
      {
        key: GLOBE_MARKER_KEYS.oktoberfest,
        title: "Oktoberfest",
        category: "FOOD",
        timing: "late Sept",
        link: "https://www.oktoberfest.de/en/",
        lat: 48.1351,
        lng: 11.5499,
        city: "Munich",
        country: "Germany",
        countryCode: "de",
        createdBy: "you",
      },
      {
        key: GLOBE_MARKER_KEYS.iceland,
        title: "Ring Road, Iceland",
        category: "ACTIVITY",
        lat: 64.9631,
        lng: -19.0208,
        city: "Reykjavik",
        country: "Iceland",
        countryCode: "is",
        createdBy: "partner",
        attachments: [
          {
            targetType: "MARKER",
            targetKey: GLOBE_MARKER_KEYS.iceland,
            filename: "iceland-route.txt",
            mime: "text/plain",
            body: "Clockwise: Golden Circle, south coast, Akureyri, Westfjords.",
          },
        ],
      },
      {
        key: GLOBE_MARKER_KEYS.dublin,
        title: "Dublin",
        category: "OTHER",
        lat: 53.3498,
        lng: -6.2603,
        city: "Dublin",
        country: "Ireland",
        countryCode: "ie",
        createdBy: "you",
      },
    ],
  };
}
