import { describe, expect, it } from "vitest";
import { renderInbox, toInboxNote, type InboxNote } from "@/lib/feedback-inbox";

const generatedAt = new Date("2026-09-08T10:00:00.000Z");

function note(overrides: Partial<InboxNote> = {}): InboxNote {
  return {
    id: "n1",
    body: "Dragging is fiddly on a phone",
    route: "/trips/t1/plan",
    pageLabel: "Plan editor",
    tripName: "Europe Summer 2026",
    authorName: "Cam",
    viewport: "390x844",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1",
    status: "OPEN",
    authoredAt: new Date("2026-09-07T08:00:00.000Z"),
    createdAt: new Date("2026-09-07T08:00:02.000Z"),
    resolvedAt: null,
    resolution: null,
    ...overrides,
  };
}

describe("renderInbox", () => {
  it("says so plainly when there is nothing to work on", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("# Feedback inbox");
    expect(md).toContain("No open feedback notes.");
  });

  it("warns that the file is generated", () => {
    expect(renderInbox([], generatedAt)).toContain(
      "Generated by `npm run feedback:pull`",
    );
  });

  it("groups open notes under their area heading", () => {
    const md = renderInbox(
      [
        note({ id: "n1", route: "/trips/t1/plan" }),
        note({ id: "n2", route: "/trips/t1/budget", body: "Totals look wrong" }),
      ],
      generatedAt,
    );
    expect(md).toContain("## Open");
    expect(md).toContain("### Plan editor");
    expect(md).toContain("### Money");
    expect(md.indexOf("### Money")).toBeGreaterThan(md.indexOf("### Plan editor"));
  });

  it("prints the id so it can be pasted into feedback:resolve", () => {
    expect(renderInbox([note()], generatedAt)).toContain("`n1`");
  });

  it("carries the circumstances of each note", () => {
    const md = renderInbox([note()], generatedAt);
    expect(md).toContain("Dragging is fiddly on a phone");
    expect(md).toContain("/trips/t1/plan");
    expect(md).toContain("Europe Summer 2026");
    expect(md).toContain("Cam");
    expect(md).toContain("2026-09-07");
  });

  it("indents a multi-line body so the markdown stays a single item", () => {
    const md = renderInbox([note({ body: "line one\nline two" })], generatedAt);
    expect(md).toContain("line one");
    expect(md).toContain("line two");
    expect(md).not.toMatch(/^line two/m);
  });

  it("keeps resolved notes below, newest resolution first, with the resolution line", () => {
    const md = renderInbox(
      [
        note({ id: "old", status: "DONE", body: "Fixed ages ago", resolvedAt: new Date("2026-09-01T00:00:00.000Z"), resolution: "Fixed in the plan editor" }),
        note({ id: "recent", status: "WONTFIX", body: "Not doing this", resolvedAt: new Date("2026-09-05T00:00:00.000Z"), resolution: "Out of scope" }),
      ],
      generatedAt,
    );
    expect(md).toContain("## Resolved");
    expect(md.indexOf("## Open")).toBeLessThan(md.indexOf("## Resolved"));
    expect(md.indexOf("Not doing this")).toBeLessThan(md.indexOf("Fixed ages ago"));
    expect(md).toContain("Out of scope");
    expect(md).toContain("Won't fix");
  });

  it("shows the device the note was written on, summarised", () => {
    const md = renderInbox([note()], generatedAt);
    expect(md).toContain("390x844 · iPhone · Safari");
    // The raw agent string is what capturing the device is *not* for.
    expect(md).not.toContain("AppleWebKit");
  });

  it("shows the viewport alone when the agent tells us nothing", () => {
    const md = renderInbox([note({ userAgent: null })], generatedAt);
    expect(md).toContain("390x844");
  });

  it("omits the device line entirely when nothing was captured", () => {
    const md = renderInbox([note({ viewport: null, userAgent: null })], generatedAt);
    expect(md).toContain("Dragging is fiddly on a phone");
    expect(md).not.toContain("__");
  });

  it("says when an offline note landed, if that was much later than it was written", () => {
    const md = renderInbox(
      [
        note({
          authoredAt: new Date("2026-09-01T08:00:00.000Z"),
          createdAt: new Date("2026-09-06T09:00:00.000Z"),
        }),
      ],
      generatedAt,
    );
    expect(md).toContain("Landed 2026-09-06");
  });

  it("stays quiet about landing when the note sent straight away", () => {
    expect(renderInbox([note()], generatedAt)).not.toContain("Landed");
  });

  it("stays quiet about landing for a lag of under a day", () => {
    const md = renderInbox(
      [
        note({
          authoredAt: new Date("2026-09-07T08:00:00.000Z"),
          createdAt: new Date("2026-09-07T20:00:00.000Z"),
        }),
      ],
      generatedAt,
    );
    expect(md).not.toContain("Landed");
  });

  it("stamps the pull with the day only, so an unchanged backlog is an unchanged file", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("pulled 2026-09-08");
    expect(md).not.toContain("2026-09-08T10:00:00.000Z");
    // Two pulls on the same day with the same notes must produce no diff.
    expect(md).toBe(renderInbox([], new Date("2026-09-08T23:59:00.000Z")));
  });

  it("counts the open notes in the summary line", () => {
    const md = renderInbox([note({ id: "a" }), note({ id: "b" })], generatedAt);
    expect(md).toContain("2 open");
  });

  it("uses unambiguous Feedback note terminology in the header", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("Resolve a Feedback note with");
    expect(md).not.toContain("Close a note with");
  });

  it("renders unknown status values as the raw status string, not undefined", () => {
    const unknownNote = {
      id: "unknown-status",
      body: "This has an unknown status",
      route: "/trips/t1/plan",
      pageLabel: "Plan editor",
      tripName: "Europe Summer 2026",
      authorName: "Cam",
      viewport: "390x844",
      userAgent: "iPhone",
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      status: "PENDING" as any,
      authoredAt: new Date("2026-09-07T08:00:00.000Z"),
      createdAt: new Date("2026-09-07T08:00:00.000Z"),
      resolvedAt: new Date("2026-09-05T00:00:00.000Z"),
      resolution: "Working on it",
    };
    const md = renderInbox([unknownNote], generatedAt);
    expect(md).toContain("PENDING");
    expect(md).not.toContain("undefined");
    expect(md).toContain("unknown-status");
  });
});

describe("toInboxNote", () => {
  const row = {
    id: "n1",
    body: "Budget totals look wrong",
    route: "/trips/t1/budget",
    pageLabel: "Budget",
    tripName: "Europe Summer 2026",
    viewport: "390x844",
    userAgent: "iPhone",
    status: "OPEN",
    authoredAt: new Date("2026-09-07T01:02:03.000Z"),
    createdAt: new Date("2026-09-07T04:05:06.000Z"),
    resolvedAt: null,
    resolution: null,
    authorName: "Cam",
  };

  it("carries every field across, unchanged", () => {
    expect(toInboxNote(row)).toEqual({
      id: "n1",
      body: "Budget totals look wrong",
      route: "/trips/t1/budget",
      pageLabel: "Budget",
      tripName: "Europe Summer 2026",
      authorName: "Cam",
      viewport: "390x844",
      userAgent: "iPhone",
      status: "OPEN",
      authoredAt: new Date("2026-09-07T01:02:03.000Z"),
      createdAt: new Date("2026-09-07T04:05:06.000Z"),
      resolvedAt: null,
      resolution: null,
    });
  });

  it("falls back to 'Traveller' when the author has no name", () => {
    expect(toInboxNote({ ...row, authorName: null }).authorName).toBe("Traveller");
  });

  it("keeps a recognised non-OPEN status", () => {
    expect(toInboxNote({ ...row, status: "WONTFIX" }).status).toBe("WONTFIX");
  });

  it("falls back to OPEN for a status the app does not recognise", () => {
    // A struck-through note with no badge explaining why is worse than an
    // unfamiliar word, and the row's `status` is a plain string from the DB.
    expect(toInboxNote({ ...row, status: "NONSENSE" }).status).toBe("OPEN");
  });

  it("preserves a resolution and its timestamp", () => {
    const resolved = toInboxNote({
      ...row,
      status: "DONE",
      resolvedAt: new Date("2026-09-09T00:00:00.000Z"),
      resolution: "fixed in 1a2b3c4",
    });
    expect(resolved.resolvedAt).toEqual(new Date("2026-09-09T00:00:00.000Z"));
    expect(resolved.resolution).toBe("fixed in 1a2b3c4");
  });
});
