import type { FeedbackStatus } from "@/lib/enums";
import { areaForRoute } from "@/lib/feedback-context";

/** A Feedback note as the inbox renders it. */
export type InboxNote = {
  id: string;
  body: string;
  route: string;
  pageLabel: string;
  tripName: string | null;
  authorName: string;
  status: FeedbackStatus;
  authoredAt: Date;
  resolvedAt: Date | null;
  resolution: string | null;
};

const STATUS_LABELS: Record<FeedbackStatus, string> = {
  OPEN: "Open",
  DONE: "Done",
  WONTFIX: "Won't fix",
};

/** "2026-09-07" — the day is enough context; the exact minute never is. */
function day(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/** Indent continuation lines so a multi-line body stays one list item. */
function indentBody(body: string): string {
  return body.trim().split("\n").join("\n  ");
}

function renderNote(note: InboxNote): string {
  const meta = [
    note.pageLabel,
    note.tripName,
    note.authorName,
    day(note.authoredAt),
  ]
    .filter(Boolean)
    .join(" · ");

  const lines = [
    `- **${meta}** — \`${note.id}\``,
    `  ${indentBody(note.body)}`,
    `  _${note.route}_`,
  ];

  if (note.status !== "OPEN") {
    const resolved = note.resolvedAt ? ` on ${day(note.resolvedAt)}` : "";
    lines.push(
      `  → **${STATUS_LABELS[note.status]}**${resolved}${note.resolution ? `: ${note.resolution}` : ""}`,
    );
  }

  return lines.join("\n");
}

/**
 * Render the Feedback inbox (ADR 0040).
 *
 * Open notes first, grouped by the area they came from and oldest first within
 * each group — the oldest annoyance has been annoying the longest. Resolved
 * notes follow as history, most recently resolved first.
 */
export function renderInbox(notes: InboxNote[], generatedAt: Date): string {
  const open = notes
    .filter((n) => n.status === "OPEN")
    .sort((a, b) => a.authoredAt.getTime() - b.authoredAt.getTime());
  const resolved = notes
    .filter((n) => n.status !== "OPEN")
    .sort(
      (a, b) => (b.resolvedAt?.getTime() ?? 0) - (a.resolvedAt?.getTime() ?? 0),
    );

  const out: string[] = [
    "# Feedback inbox",
    "",
    "Feedback notes written from inside TEEPEE (ADR 0040). **Generated by " +
      "`npm run feedback:pull` — do not edit by hand; the database is the truth " +
      "and this file is its printout.** Close a note with " +
      "`npm run feedback:resolve -- <id> --note \"what you did\"`.",
    "",
    `_${open.length} open, ${resolved.length} resolved · pulled ${generatedAt.toISOString()}_`,
    "",
    "## Open",
    "",
  ];

  if (open.length === 0) {
    out.push("No open feedback notes.", "");
  } else {
    const areas = new Map<string, InboxNote[]>();
    for (const note of open) {
      const area = areaForRoute(note.route);
      const bucket = areas.get(area);
      if (bucket) bucket.push(note);
      else areas.set(area, [note]);
    }
    for (const [area, bucket] of areas) {
      out.push(`### ${area}`, "");
      for (const note of bucket) out.push(renderNote(note), "");
    }
  }

  if (resolved.length > 0) {
    out.push("## Resolved", "");
    for (const note of resolved) out.push(renderNote(note), "");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}
