import { describe, expect, it } from "vitest";
import { renderInbox, type InboxNote } from "@/lib/feedback-inbox";

const generatedAt = new Date("2026-09-08T10:00:00.000Z");

function note(overrides: Partial<InboxNote> = {}): InboxNote {
  return {
    id: "n1",
    body: "Dragging is fiddly on a phone",
    route: "/trips/t1/plan",
    pageLabel: "Plan editor",
    tripName: "Europe Summer 2026",
    authorName: "Cam",
    status: "OPEN",
    authoredAt: new Date("2026-09-07T08:00:00.000Z"),
    resolvedAt: null,
    resolution: null,
    ...overrides,
  };
}

describe("renderInbox", () => {
  it("says so plainly when there is nothing to work on", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("# Feedback inbox");
    expect(md).toContain("No open feedback notes.");
  });

  it("warns that the file is generated", () => {
    expect(renderInbox([], generatedAt)).toContain(
      "Generated by `npm run feedback:pull`",
    );
  });

  it("groups open notes under their area heading", () => {
    const md = renderInbox(
      [
        note({ id: "n1", route: "/trips/t1/plan" }),
        note({ id: "n2", route: "/trips/t1/budget", body: "Totals look wrong" }),
      ],
      generatedAt,
    );
    expect(md).toContain("## Open");
    expect(md).toContain("### Plan editor");
    expect(md).toContain("### Money");
    expect(md.indexOf("### Money")).toBeGreaterThan(md.indexOf("### Plan editor"));
  });

  it("prints the id so it can be pasted into feedback:resolve", () => {
    expect(renderInbox([note()], generatedAt)).toContain("`n1`");
  });

  it("carries the circumstances of each note", () => {
    const md = renderInbox([note()], generatedAt);
    expect(md).toContain("Dragging is fiddly on a phone");
    expect(md).toContain("/trips/t1/plan");
    expect(md).toContain("Europe Summer 2026");
    expect(md).toContain("Cam");
    expect(md).toContain("2026-09-07");
  });

  it("indents a multi-line body so the markdown stays a single item", () => {
    const md = renderInbox([note({ body: "line one\nline two" })], generatedAt);
    expect(md).toContain("line one");
    expect(md).toContain("line two");
    expect(md).not.toMatch(/^line two/m);
  });

  it("keeps resolved notes below, newest resolution first, with the resolution line", () => {
    const md = renderInbox(
      [
        note({ id: "old", status: "DONE", body: "Fixed ages ago", resolvedAt: new Date("2026-09-01T00:00:00.000Z"), resolution: "Fixed in the plan editor" }),
        note({ id: "recent", status: "WONTFIX", body: "Not doing this", resolvedAt: new Date("2026-09-05T00:00:00.000Z"), resolution: "Out of scope" }),
      ],
      generatedAt,
    );
    expect(md).toContain("## Resolved");
    expect(md.indexOf("## Open")).toBeLessThan(md.indexOf("## Resolved"));
    expect(md.indexOf("Not doing this")).toBeLessThan(md.indexOf("Fixed ages ago"));
    expect(md).toContain("Out of scope");
    expect(md).toContain("Won't fix");
  });

  it("counts the open notes in the summary line", () => {
    const md = renderInbox([note({ id: "a" }), note({ id: "b" })], generatedAt);
    expect(md).toContain("2 open");
  });

  it("uses unambiguous Feedback note terminology in the header", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("Resolve a Feedback note with");
    expect(md).not.toContain("Close a note with");
  });

  it("renders unknown status values as the raw status string, not undefined", () => {
    const unknownNote = {
      id: "unknown-status",
      body: "This has an unknown status",
      route: "/trips/t1/plan",
      pageLabel: "Plan editor",
      tripName: "Europe Summer 2026",
      authorName: "Cam",
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      status: "PENDING" as any,
      authoredAt: new Date("2026-09-07T08:00:00.000Z"),
      resolvedAt: new Date("2026-09-05T00:00:00.000Z"),
      resolution: "Working on it",
    };
    const md = renderInbox([unknownNote], generatedAt);
    expect(md).toContain("PENDING");
    expect(md).not.toContain("undefined");
    expect(md).toContain("unknown-status");
  });
});
