import { describe, expect, it } from "vitest";
import { renderInbox, toInboxNote, type InboxNote } from "@/lib/feedback-inbox";
import { siteOf } from "@/lib/feedback-site";

const generatedAt = new Date("2026-09-08T10:00:00.000Z");

function note(
  overrides: Partial<Omit<InboxNote, "site">> & { site?: string | null } = {},
): InboxNote {
  const { site, ...rest } = overrides;
  return {
    id: "n1",
    body: "Dragging is fiddly on a phone",
    route: "/trips/t1/plan",
    pageLabel: "Plan editor",
    tripName: "Europe Summer 2026",
    authorName: "Cam",
    viewport: "390x844",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1",
    status: "OPEN",
    authoredAt: new Date("2026-09-07T08:00:00.000Z"),
    createdAt: new Date("2026-09-07T08:00:02.000Z"),
    resolvedAt: null,
    resolution: null,
    site: siteOf(site === undefined ? "main" : site),
    ...rest,
  };
}

describe("renderInbox", () => {
  it("says so plainly when there is nothing to work on", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("# Feedback inbox");
    expect(md).toContain("No open feedback notes.");
  });

  it("warns that the file is generated", () => {
    expect(renderInbox([], generatedAt)).toContain(
      "Generated by `npm run feedback:pull`",
    );
  });

  it("groups open notes under their area heading", () => {
    const md = renderInbox(
      [
        note({ id: "n1", route: "/trips/t1/plan" }),
        note({ id: "n2", route: "/trips/t1/budget", body: "Totals look wrong" }),
      ],
      generatedAt,
    );
    expect(md).toContain("## Open");
    expect(md).toContain("### Plan editor");
    expect(md).toContain("### Money");
    expect(md.indexOf("### Money")).toBeGreaterThan(md.indexOf("### Plan editor"));
  });

  it("prints the id so it can be pasted into feedback:resolve", () => {
    expect(renderInbox([note()], generatedAt)).toContain("`n1`");
  });

  it("carries the circumstances of each note", () => {
    const md = renderInbox([note()], generatedAt);
    expect(md).toContain("Dragging is fiddly on a phone");
    expect(md).toContain("/trips/t1/plan");
    expect(md).toContain("Europe Summer 2026");
    expect(md).toContain("Cam");
    expect(md).toContain("2026-09-07");
  });

  it("indents a multi-line body so the markdown stays a single item", () => {
    const md = renderInbox([note({ body: "line one\nline two" })], generatedAt);
    expect(md).toContain("line one");
    expect(md).toContain("line two");
    expect(md).not.toMatch(/^line two/m);
  });

  it("counts resolved notes in the summary but does not list them", () => {
    const md = renderInbox(
      [
        note({ id: "open1", body: "Still broken" }),
        note({ id: "old", status: "DONE", body: "Fixed ages ago", resolvedAt: new Date("2026-09-01T00:00:00.000Z"), resolution: "Fixed in the plan editor" }),
        note({ id: "recent", status: "WONTFIX", body: "Not doing this", resolvedAt: new Date("2026-09-05T00:00:00.000Z"), resolution: "Out of scope" }),
      ],
      generatedAt,
    );
    expect(md).toContain("2 resolved");
    expect(md).toContain("Still broken");
    expect(md).not.toContain("## Resolved");
    expect(md).not.toContain("Fixed ages ago");
    expect(md).not.toContain("Not doing this");
  });

  it("shows the device the note was written on, summarised", () => {
    const md = renderInbox([note()], generatedAt);
    expect(md).toContain("390x844 · iPhone · Safari");
    // The raw agent string is what capturing the device is *not* for.
    expect(md).not.toContain("AppleWebKit");
  });

  it("shows the viewport alone when the agent tells us nothing", () => {
    const md = renderInbox([note({ userAgent: null })], generatedAt);
    expect(md).toContain("390x844");
  });

  it("omits the device line entirely when nothing was captured", () => {
    const md = renderInbox([note({ viewport: null, userAgent: null })], generatedAt);
    expect(md).toContain("Dragging is fiddly on a phone");
    expect(md).not.toContain("__");
  });

  it("says when an offline note landed, if that was much later than it was written", () => {
    const md = renderInbox(
      [
        note({
          authoredAt: new Date("2026-09-01T08:00:00.000Z"),
          createdAt: new Date("2026-09-06T09:00:00.000Z"),
        }),
      ],
      generatedAt,
    );
    expect(md).toContain("Landed 2026-09-06");
  });

  it("stays quiet about landing when the note sent straight away", () => {
    expect(renderInbox([note()], generatedAt)).not.toContain("Landed");
  });

  it("stays quiet about landing for a lag of under a day", () => {
    const md = renderInbox(
      [
        note({
          authoredAt: new Date("2026-09-07T08:00:00.000Z"),
          createdAt: new Date("2026-09-07T20:00:00.000Z"),
        }),
      ],
      generatedAt,
    );
    expect(md).not.toContain("Landed");
  });

  it("stamps the pull with the day only, so an unchanged backlog is an unchanged file", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("pulled 2026-09-08");
    expect(md).not.toContain("2026-09-08T10:00:00.000Z");
    // Two pulls on the same day with the same notes must produce no diff.
    expect(md).toBe(renderInbox([], new Date("2026-09-08T23:59:00.000Z")));
  });

  it("counts the open notes in the summary line", () => {
    const md = renderInbox([note({ id: "a" }), note({ id: "b" })], generatedAt);
    expect(md).toContain("2 open");
  });

  it("uses unambiguous Feedback note terminology in the header", () => {
    const md = renderInbox([], generatedAt);
    expect(md).toContain("Resolve a Feedback note with");
    expect(md).not.toContain("Close a note with");
  });

  it("splits open notes into site sections, Beta first, then Main, then others", () => {
    const md = renderInbox([
      note({ id: "m1", site: "main" }),
      note({ id: "b1", site: "beta" }),
      note({ id: "x1", site: "feat/x" }),
    ], new Date("2026-09-26"));
    const beta = md.indexOf("## Open · Beta");
    const main = md.indexOf("## Open · Main");
    const other = md.indexOf("## Open · feat/x");
    expect(beta).toBeGreaterThan(-1);
    expect(main).toBeGreaterThan(beta);
    expect(other).toBeGreaterThan(main);
    expect(md.slice(beta, main)).toContain("`b1`");
  });

  it("a note with no site is Main, and an absent site gets no empty section", () => {
    const md = renderInbox([note({ id: "old", site: null })], new Date("2026-09-26"));
    expect(md).toContain("## Open · Main");
    expect(md).not.toContain("## Open · Beta");
  });

  it("shows open counts per site in the header", () => {
    const md = renderInbox([note({ site: "beta" }), note({ site: "beta" }), note({ site: null })], new Date("2026-09-26"));
    expect(md).toContain("_3 open (Beta 2 · Main 1), 0 resolved · pulled 2026-09-26_");
  });

  it("lists Needs-review notes in their own section after Open, and counts them in the summary", () => {
    const md = renderInbox(
      [
        note({ id: "a", status: "OPEN" }),
        note({ id: "b", status: "NEEDS_REVIEW", authorName: "Tester", body: "Tester remark" }),
      ],
      new Date("2026-09-29"),
    );
    expect(md).toContain("_1 open (Main 1), 1 needs review, 0 resolved · pulled 2026-09-29_");
    const open = md.indexOf("## Open · Main");
    const review = md.indexOf("## Needs review");
    expect(open).toBeGreaterThan(-1);
    expect(open).toBeLessThan(review);
    // The tester's note sits under Needs review, not under Open.
    expect(md.slice(open, review)).not.toContain("`b`");
    expect(md.slice(review)).toContain("`b`");
    expect(md.slice(review)).toContain("Tester remark");
    expect(md).toContain("Not backlog yet");
    expect(md).toMatch(/## Needs review\n\n.+\n\n### Plan editor\n\n- \*\*Main · Plan editor · Europe Summer 2026 · Tester · 2026-09-07\*\* — `b`/);
    expect(md).not.toContain("## Other");
    // A Needs-review note carries no resolution badge.
    expect(md).not.toContain("**Needs review**");
  });

  it("groups Needs-review notes by area and orders them oldest first", () => {
    const md = renderInbox(
      [
        note({ id: "late", status: "NEEDS_REVIEW", route: "/trips/t1/plan", authoredAt: new Date("2026-09-20T00:00:00Z") }),
        note({ id: "money", status: "NEEDS_REVIEW", route: "/trips/t1/budget", authoredAt: new Date("2026-09-15T00:00:00Z") }),
        note({ id: "early", status: "NEEDS_REVIEW", route: "/trips/t1/plan", authoredAt: new Date("2026-09-10T00:00:00Z") }),
      ],
      new Date("2026-09-29"),
    );
    const review = md.slice(md.indexOf("## Needs review"));
    expect(review.indexOf("### Plan editor")).toBeLessThan(review.indexOf("### Money"));
    expect(review.indexOf("`early`")).toBeLessThan(review.indexOf("`late`"));
    expect(review.indexOf("`late`")).toBeLessThan(review.indexOf("### Money"));
  });

  it("with only Needs-review notes, says there is no open work and still counts them", () => {
    const md = renderInbox([note({ id: "b", status: "NEEDS_REVIEW" })], new Date("2026-09-29"));
    expect(md).toContain("_0 open, 1 needs review, 0 resolved · pulled 2026-09-29_");
    expect(md).toContain("No open feedback notes.");
    expect(md.indexOf("## Open")).toBeLessThan(md.indexOf("## Needs review"));
  });

  it("leaves the summary line unchanged when nothing needs review", () => {
    const md = renderInbox([note()], new Date("2026-09-29"));
    expect(md).toContain("_1 open (Main 1), 0 resolved · pulled 2026-09-29_");
    expect(md).not.toContain("needs review");
    expect(md).not.toContain("## Needs review");
  });

  it("keeps an unknown status under Other, after Needs review", () => {
    const md = renderInbox(
      [
        note({ id: "b", status: "NEEDS_REVIEW" }),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        note({ id: "weird", status: "PENDING" as any }),
      ],
      new Date("2026-09-29"),
    );
    expect(md.indexOf("## Needs review")).toBeLessThan(md.indexOf("## Other"));
    expect(md.slice(md.indexOf("## Other"))).toContain("`weird`");
  });

  it("tells the reader how to accept a note in the header", () => {
    expect(renderInbox([], generatedAt)).toContain("npm run feedback:accept -- <id>");
  });

  it("renders unknown status values as the raw status string, not undefined", () => {
    const unknownNote = {
      id: "unknown-status",
      body: "This has an unknown status",
      route: "/trips/t1/plan",
      pageLabel: "Plan editor",
      tripName: "Europe Summer 2026",
      authorName: "Cam",
      viewport: "390x844",
      userAgent: "iPhone",
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      status: "PENDING" as any,
      authoredAt: new Date("2026-09-07T08:00:00.000Z"),
      createdAt: new Date("2026-09-07T08:00:00.000Z"),
      resolvedAt: new Date("2026-09-05T00:00:00.000Z"),
      resolution: "Working on it",
      site: "main",
    };
    const md = renderInbox([unknownNote], generatedAt);
    expect(md).toContain("PENDING");
    expect(md).not.toContain("undefined");
    expect(md).toContain("unknown-status");
  });
});

describe("toInboxNote", () => {
  const row = {
    id: "n1",
    body: "Budget totals look wrong",
    route: "/trips/t1/budget",
    pageLabel: "Budget",
    tripName: "Europe Summer 2026",
    viewport: "390x844",
    userAgent: "iPhone",
    status: "OPEN",
    authoredAt: new Date("2026-09-07T01:02:03.000Z"),
    createdAt: new Date("2026-09-07T04:05:06.000Z"),
    resolvedAt: null,
    resolution: null,
    authorName: "Cam",
    site: "beta",
  };

  it("carries every field across, unchanged", () => {
    expect(toInboxNote(row)).toEqual({
      id: "n1",
      body: "Budget totals look wrong",
      route: "/trips/t1/budget",
      pageLabel: "Budget",
      tripName: "Europe Summer 2026",
      authorName: "Cam",
      viewport: "390x844",
      userAgent: "iPhone",
      status: "OPEN",
      authoredAt: new Date("2026-09-07T01:02:03.000Z"),
      createdAt: new Date("2026-09-07T04:05:06.000Z"),
      resolvedAt: null,
      resolution: null,
      site: "beta",
    });
  });

  it("maps a null stored site to Main", () => {
    expect(toInboxNote({ ...row, site: null }).site).toBe("main");
  });

  it("falls back to 'Traveller' when the author has no name", () => {
    expect(toInboxNote({ ...row, authorName: null }).authorName).toBe("Traveller");
  });

  it("keeps NEEDS_REVIEW as its own status", () => {
    expect(toInboxNote({ ...row, status: "NEEDS_REVIEW" }).status).toBe("NEEDS_REVIEW");
  });

  it("keeps a recognised non-OPEN status", () => {
    expect(toInboxNote({ ...row, status: "WONTFIX" }).status).toBe("WONTFIX");
  });

  it("falls back to OPEN for a status the app does not recognise", () => {
    // A struck-through note with no badge explaining why is worse than an
    // unfamiliar word, and the row's `status` is a plain string from the DB.
    expect(toInboxNote({ ...row, status: "NONSENSE" }).status).toBe("OPEN");
  });

  it("preserves a resolution and its timestamp", () => {
    const resolved = toInboxNote({
      ...row,
      status: "DONE",
      resolvedAt: new Date("2026-09-09T00:00:00.000Z"),
      resolution: "fixed in 1a2b3c4",
    });
    expect(resolved.resolvedAt).toEqual(new Date("2026-09-09T00:00:00.000Z"));
    expect(resolved.resolution).toBe("fixed in 1a2b3c4");
  });
});
